### ISSUE TITLE
Question about security

### ISSUE THREAD

**Issue by MaxGuitet** [copleykj/socialize-messaging#21]
Hello,
I just started using this package, really like all the functionalities you have implemented, very powerful!
Though I have some question for my own knowledge. Reading through the code, I noticed that the Conversations collection for instance can be inserted from the client (`allow` is set to true if logged in). Isn't there a risk for a client to access it from the console and, for instance, create a Conversation passing another userId?
Also, the `participants` methods returns the full user object. The thing is we want to reduce the number of fields passed, both for security and performance reasons. How would you recommend to tweak that? Using a different publication? 
And finally, you insert a `_document` object in the collection which is similar to the root object, what is the reason for that?

Regards,

Max

**Comment by copleykj** [comment]
Hi, Glad the package is of use to you.

As far as client side operations go, yes all the packages in the set make complete use of client side inserts and updates. The security implications of this are mitigated through the use of both SimpleSchema, and allow rules. The allow rules are purposefully simple and make minor checks that can not be done through SimpleSchema which handles everything else. The case you mention with conversations being inserted wouldn't allow the user to input an arbitrary userId because SimpleSchema sets this server side. The client could try to do this in the console, and it may even look for a brief second like they succeeded, but once the server code runs the client side cache would be invalidated and they would see their operation failed.

With the methods that return unfiltered documents, right now the publications are probably the easiest way to accomplish this. That being said, I'd be more than happy to take pull requests for a way to restrict the fields returned by the method.

Finally the `_document` property doesn't get inserted into the database, but rather is a property on the model, created and used by BaseModel for diffing purposes.

Hopefully this is adequate information, If you have any other questions just let me know.

**Comment by MaxGuitet** [comment]
Hello,

Thanks for your quick reply. SimpleSchema is indeed a strong enough package for checking. I'll carry on with that and see if it needs further security. Same for the publications, if I find any benefit in restricting the publication I'll make a pull request.

Regards
