### ISSUE TITLE
Is there a demo app available for socialize?

### ISSUE THREAD

**Issue by derwaldgeist** [copleykj/socialize-messaging#6]
Hi @copleykj: I would like to deep-dive into this package, as I need a robust messaging framework for my application. But, to be honest, I find it quite hard to understand how everything fits together. Is there a kind of demo-app available which demonstrates the capabilities of the socialize ecosystem? The documentation in Github is quite technology-oriented, but I am missing the "big picture", i.e. concrete use-cases. KR, Tom

**Comment by derwaldgeist** [comment]
I now found this repo
https://github.com/copleykj/socialize-messaging-demo

but the app is broken

```js
   While building the application:
   /Users/waldgeist/Documents/Development/htdocs/tests/socialize-messaging-demo/stylesheets/main.scss:1:9: Scss
   compiler error: file to import not found or unreadable:
   .meteor/local/build/programs/server/assets/packages/meta_susy/susy
   Current dir: /Users/waldgeist/Documents/Development/htdocs/tests/socialize-messaging-demo/stylesheets/
```

**Comment by kaiyes** [comment]
@derwaldgeist   I will try to make a quick demo. He is super busy.

**Comment by kaiyes** [comment]
check this out

**Comment by kaiyes** [comment]
@copleykj  may be you can add on this. I just used the `sendMessage` and `Meteor.conversation.find()` here. I couldn't get the `Meteor.user().findExistingConversationWithUsers` to work. Sometimes it worked, sometimes it didn't. So I had to get a work-around by creating another `ChatInvites` collection. I blame my own inability for that. Now that a base has been made. Could you please fork and make something out of this showcasing all the methods ? 
Thanks

**Comment by copleykj** [comment]
I have some more time over the next week that I don't normally have so I'm going to try to dive into this. For now I've made some major updates to the documentation. Probably still not perfect but I think it should help understand the package much better. If you spot any glaring omissions, pull requests are welcome.

**Comment by limingth** [comment]
Any runnable(live) demos for your package?

**Comment by kaiyes** [comment]
@limingth  I made a small demo with this package. Although not official one, it might help you. it needs at least two user to start talking to each other. 

http://chatdemo-social.meteor.com/ 
https://github.com/kaiyes/chatDemo/

**Comment by limingth** [comment]
Cool. Thanks @kaiyes

**Comment by kaiyes** [comment]
I just used these methods and nothing else. 

`var conversation = new Conversation().save();`

`conversation.addParticipant( Meteor.users.findOne({username:"JohnDoe"}) );`

`conversation.sendMessage("Hello World!");`

`var conversation = Meteor.conversations.findOne(); // Single Conversation Instance`

`var conversations = Meteor.conversations.find(); // Cursor Returning Conversation Instances`

**Comment by limingth** [comment]
@kaiyes Have you tested all/other socialize-xxx packages?  I am trying to use friendship and likeable package in my project.

**Comment by kaiyes** [comment]
There is a youtube video where copley himself explained the friendship package very well. https://www.youtube.com/watch?v=ENPVrGmod28

**Comment by kaiyes** [comment]
I am using the friendship package in a app. So in my app it works like this....if  user1 is friends with user2 only then they can see each other's photo and that's about it

**Comment by copleykj** [comment]
I'm trying to cram a whole lot of work into the little bit of extra time I have this week. I should be able to have a halfway decent demo working in the next week. At least that is the hope. Once I have something pieced together I'll push it to a repo and work on it in the open and maybe we can polish it off together.

**Comment by limingth** [comment]
@copleykj Thanks, I am deeply impressed by your fantastic work although I have to debug these days by myself to use it in my project. I think there should be a socialize-groups package to let user join/leaveGroup.  Are you planning to do that?

**Comment by copleykj** [comment]
Do you mean groups as in like facebook has?

**Comment by limingth** [comment]
Yes. we are doing a simple [demo](http://maodoufriends.meteor.com/) using our own friends/groups package. But I wish someday I can switch to your packages. There is a lot we can learn from your design thinking.

**Comment by copleykj** [comment]
I've had a couple thoughts on that type of package.. As of right now I see it requiring a bit of work.. First I think I would need to refactor the "requests" part out of the friendships package and into a package called requestable so that you could request both friendships and group access. Then I would probably create another package called inviteable that would allow users to invite other users to join a group.

The good news is that I need to do all of this anyway for another package that I have planned that will enable event listings so it's already planned work, I'm just not sure right now when I'll get the time to complete it. Unfortunately I am at the mercy of paid work at the moment. If I could find a way to get paid for working on the socialize packages I'd quit my second job tomorrow :smiley:

**Comment by jarrodoxical** [comment]
@derwaldgeist I was able to get the official demo app running by opening up another browser and the code fuses a room together where two can chat. The meteor-toys mongol package also helps you sign in/out on the same browser and get two users which will achieve the same end.

[GitterClone](http://gitterclone.meteor.com) 

I made an unofficial demo that touches on friendships and messaging, having to alter the package slightly to make my specific room functions. It is an lowly replica of [gitter.im](http://gitter.im) chat service using the socialize package, I will put the code up very shortly.

@copleykj Thanks for all your awesome thinking and designing that went into this.

**Comment by copleykj** [comment]
@jarrodoxical very nice start, I look forward to seeing this progress

**Comment by StorytellerCZ** [comment]
I'm building packages that put socialize packages to work. They are divided into server and client parts. The goal is to create basic React components that anyone can insert into their app where they want it. I'm currently working on the messaging part. Once I have that I will build a quick demo. My goal is to create a demo that can be used as a starting point for apps.
There is still a lot of work to be done, but feel free to check it out (any help would be appreciated):
https://atmospherejs.com/storyteller

**Comment by kaiyes** [comment]
awesome @StorytellerCZ  waiting for that

**Comment by StorytellerCZ** [comment]
Just finished messaging:
https://github.com/StorytellerCZ/meteor-messaging-react-materialize
I will build the sample app after I improve it a bit more.

**Comment by StorytellerCZ** [comment]
The app:
https://github.com/StorytellerCZ/Socialize-starter

Still a lot of work to do, but feel free to join and fix/improve my code.

**Comment by kaiyes** [comment]
@StorytellerCZ  awesome!! gonna take a look now. Have you implemented notification yet?

**Comment by StorytellerCZ** [comment]
@kaiyes Only one small one. But that is a good ticket to open up there.

**Comment by kaiyes** [comment]
@StorytellerCZ  nice work on the wiki mate ! Is there any chance you can  spin up a demo app with blaze in ? I have https://github.com/kaiyes/chatDemo/ where I show a basic working copy. But it was a quick one to help people get started and pub sub wasn't there. Now that pub sub wiki for messaging has been added, may be its a chance to do it. 

@copleykj  Could you please spin up a demo video for messaging like you did before ? This is the most asked thing in this thread,and judging by the sheer number of people I see in that small chat demo app of mine, I guess its very much needed.  The pub sub mechanism for this messaging package is great for a video tutorial.

**Comment by kaiyes** [comment]
just take a look how many people are interested !! 
![screen shot 2016-03-08 at 9 29 38 pm]
![screen shot 2016-03-08 at 9 29 46 pm](https://cloud.githubusercontent.com/assets/5293742/13606181/3632aeb0-e575-11e5-83a5-8e4cb6e796ea.png)
(https://cloud.githubusercontent.com/assets/5293742/13606154/199b6a9e-e575-11e5-9445-d6cc16660097.png)
![screen shot 2016-03-08 at 9 30 15 pm](https://cloud.githubusercontent.com/assets/5293742/13606158/1da988b4-e575-11e5-9f52-7cedf7c680f4.png)

**Comment by kaiyes** [comment]
![screen shot 2016-03-08 at 9 30 08 pm](https://cloud.githubusercontent.com/assets/5293742/13606267/9dd821a8-e575-11e5-9718-f987ef5b2cbc.png)

**Comment by StorytellerCZ** [comment]
@kaiyes Right now I don't plan to do a Blaze front-ent for my packages (I'm too busy on another project from which the Socialize-starter came to be), but the structure allows for easy plug-in if you want to do it.

As for the wiki I have only copied and improved (adding checks) the current publications in this package. My package has [2 extra publications](https://github.com/StorytellerCZ/meteor-messaging-server/blob/master/messaging-server.js). I've added it there in preparation for time when they will be removed from from this package as mentioned in #8. Going forward removing publish functions from socialize package seems to be the direction @copleykj wants to go. If not then it would require making sure that checks are included so that `audit-argument-checks` is satisfied. My server packages for messaging and other socialize packages are ready to be updated when the time comes to include the removed publications and some more.

**Comment by copleykj** [comment]
Hey guys so I would really love to be working on this stuff a lot more. Unfortunately at this point I've got about 15 hours a week max that I get to work on code, and that includes paid projects. I do have a good chunk of social network to demonstrate most of these packages done. It's just finding the 50+ hours it will take to finish it off.

If anyone wants to fund my time to work towards finishing this or working to further the packages you can do that via bitcoin or paypal.

Bitcoin: 1HXhdSCpXe8WKy9vYsu597ABBQ359z7fhU

Paypal: copleykj@gmail.com

These are exciting times for Meteor, but I really think that the move forward may outpace the time I have to move the packages forward. Soon 1.3 will have proper module support, then soon after Apollo will bring a new data layer.. That's quite a bit of work moving forward for a set of packages this large and I haven't even started to work on the groups and event listing packages.

**Comment by copleykj** [comment]
Thanks @StorytellerCZ for the very generous contribution. I'm hoping to devote a few hours to resolving the publication issues this afternoon/evening. No guarantees at this point though since I'm working off of 3 hours a sleep :-P

I've also got a trello board going to keep track of things. https://trello.com/b/RkEYuw8c 

At this point I'm mostly using it just to keep track of package versions. If you would like to be added to the team/board, just let me know.

**Comment by copleykj** [comment]
I've pushed commits that remove publications from the final packages that still had them. There are still stateful publications in the messaging package but they are not used to push data to the client.

I'll try to get these changes released asap but it'll likely be Monday as I'm working 36 hours between tonight and Sunday night.

After that my plan is to continue working on the blazed based social network demo for the packages. If things go well I should make a bit of progress on Monday/Tuesday since I have those days off, but you never can tell how much time you will get to do things having a newborn.

**Comment by kaiyes** [comment]
@jarrodoxical  , @limingth , @derwaldgeist a new slack channel for all the discussions have been opened for us by @copleykj . https://meteor-socialize.slack.com so Do join and we can discuss things there

**Comment by copleykj** [comment]
Ok guys, I'm closing this and we can discuss anything like this on slack.
