### ISSUE TITLE
Exception in queued task: Error: Removed nonexistent document aEQFC7wXfohMXSpox

### ISSUE THREAD

**Issue by theodorDiaconu** [copleykj/socialize-messaging#9]
This is what happens when sending a message.

Full error stack:
```
I20160205-01:58:00.020(2)? Exception in queued task: Error: Removed nonexistent document aEQFC7wXfohMXSpox
I20160205-01:58:00.020(2)?     at [object Object]._.extend.removed (livedata_server.js:199:17)
I20160205-01:58:00.020(2)?     at [object Object]._.extend.removed (livedata_server.js:388:10)
I20160205-01:58:00.020(2)?     at [object Object]._.extend.removed (livedata_server.js:1269:19)
I20160205-01:58:00.020(2)?     at collection.find.observeChanges.removed (packages/tmeasday_publish-with-relations/packages/tmeasday_publish-with-relations.js:29:1)
I20160205-01:58:00.021(2)?     at packages/mongo/observe_multiplex.js:183:1
I20160205-01:58:00.021(2)?     at Array.forEach (native)
I20160205-01:58:00.021(2)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20160205-01:58:00.021(2)?     at Object.task (packages/mongo/observe_multiplex.js:177:1)
I20160205-01:58:00.021(2)?     at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
I20160205-01:58:00.021(2)?     at packages/meteor/fiber_helpers.js:125:1
```

**Comment by copleykj** [comment]
This seems to be an issue with the publication. Would be very helpful to have a reproduction to get a full understanding of what might cause it.

**Comment by theodorDiaconu** [comment]
@copleykj after hours of sweating and debugging I thought: why don't I create my own publication for "messages" and subscribe to it, to see all messages. Then it worked. SO what fixed it was passing {limit: ...} when subscribing to messagesFor. 

I believe we need a fallback for this limit. What do you think ?

**Comment by copleykj** [comment]
That is very strange that when subscribing to all messages you get this error, but when using limit you don't.. This should actually be the exact opposite case since there shouldn't be any removed callbacks on the publication since the whole set should be published and there shouldn't be any "falling off" when new messages are added.

As for the publication, in the very near future the included publications are going to be removed to allow for the use of other join packages. When using these publications though I definitely recommend using a limit clause, as fetching all messages as the conversation grows is going to get progressively slower in a very linear fashion. I personally like to limit messages to between 15 - 30 and then have the option to load older messages.. This strikes a nice balance of having some history while still limiting the perception of your app loading slowly.

**Comment by theodorDiaconu** [comment]
@copleykj I think the problem might be becacuse when we publish to messagesFor, options.limit is undefined. That's where things break I suppose.

**Comment by StorytellerCZ** [comment]
#8

**Comment by copleykj** [comment]
Publications removed in next release.
